"""
schemas.py
----------
Pydantic models defining the request and response shapes for the
AI-Powered Restaurant Recommendation API (Phase 4).
"""

from typing import Optional, List
from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Request Model
# ---------------------------------------------------------------------------

class RecommendationRequest(BaseModel):
    """Payload sent by the client to the POST /api/recommend endpoint."""

    location: Optional[str] = Field(
        default=None,
        description="City or neighbourhood to filter restaurants by (case-insensitive substring match).",
        examples=["Banashankari"],
    )
    cuisine: Optional[str] = Field(
        default=None,
        description="Cuisine type to filter by (e.g. 'Chinese', 'North Indian').",
        examples=["Chinese"],
    )
    budget: Optional[str] = Field(
        default=None,
        description="Budget tier: 'low' (<500), 'medium' (500-1500), or 'high' (>1500).",
        examples=["medium"],
    )
    min_rating: float = Field(
        default=0.0,
        ge=0.0,
        le=5.0,
        description="Minimum acceptable restaurant rating on a 0-5 scale.",
        examples=[4.0],
    )
    notes: Optional[str] = Field(
        default="",
        description="Free-text qualitative preferences (e.g. 'family friendly', 'outdoor seating').",
        examples=["family friendly, outdoor seating"],
    )

    @field_validator("budget", mode="before")
    @classmethod
    def validate_budget(cls, v):
        if v is None:
            return v
        v = v.strip().lower()
        if v not in ("low", "medium", "high", ""):
            raise ValueError("budget must be one of: 'low', 'medium', 'high'")
        return v if v else None


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class RestaurantRecommendation(BaseModel):
    """A single AI-ranked restaurant card returned to the client."""

    name: str = Field(description="Restaurant name.")
    cuisine: str = Field(description="Comma-separated list of cuisines served.")
    rating: float = Field(description="Restaurant rating (0-5).")
    estimated_cost: int = Field(description="Approximate cost for two people (INR).")
    ai_explanation: str = Field(
        description="Personalised 2-3 sentence explanation generated by the LLM."
    )


class RecommendationResponse(BaseModel):
    """Top-level response envelope returned by POST /api/recommend."""

    success: bool = Field(default=True)
    count: int = Field(description="Number of recommendations returned.")
    recommendations: List[RestaurantRecommendation] = Field(
        description="Ranked list of restaurant recommendations."
    )
    message: Optional[str] = Field(
        default=None,
        description="Human-readable status or warning message (e.g. no matches found).",
    )


class LocationsResponse(BaseModel):
    """Response returned by GET /api/locations."""

    locations: List[str] = Field(description="Sorted list of unique locations in the dataset.")


class CuisinesResponse(BaseModel):
    """Response returned by GET /api/cuisines."""

    cuisines: List[str] = Field(description="Sorted list of unique cuisines in the dataset.")
